---
- name: Check if rke2_node_type is valid
  fail:
    msg: "Only 'agent' and 'server' are valid for rke2_node_type - Please make sure to set the variable for each node!"
  when:
    - rke2_node_type != "server"
    - rke2_node_type != "agent"
