---
# tasks file for rke2-ansible
#TODO: 
# - Disable SWAP
# - Link Kubectl config on nodes
# - Fix downloaded kubeconfig file to point to correct server

- include_tasks: check-variables.yml

- include_tasks: find-cluster-token.yml
  when:
    - not first_node_install

- include_tasks: install-kube-vip.yml
  when: 
    - first_node_install
    - control_plane_vip is not none

- include_tasks: install-kubectl.yml
  when: 
    - kubectl_install_on_nodes

- include_tasks: install-rke2.yml
