---
# tasks file for rke2-ansible
#TODO: 
# - Disable SWAP

- include_tasks: find-cluster-token.yml
  when:
    - not first_node_install

- include_tasks: install-kubectl.yml
  when: 
    - kubectl_install_on_nodes

- include_tasks: install-rke2.yml
