---

- include_tasks: check-variables.yml

- include_tasks: find-cluster-token.yml
  when:
    - not first_node_install

- include_tasks: install-kube-vip.yml
  when:
    - first_node_install
    - control_plane_vip is not none

- include_tasks: install-kubectl.yml
  when:
    - kubectl_install_on_nodes

- include_tasks: install-rke2.yml

- include_tasks: install-longhorn-dependencies.yml
  when: install_longhorn_dependencies

- include_tasks: install-calicoctl.yml
  when: 
    - cni_plugin == "calico"
    - install_calicoctl
